services:
  - type: web
    name: smile-design-ai
    runtime: docker
    rootDir: . # Root directory is now . because Dockerfile needs access to both frontend and backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: REPLICATE_API_TOKEN
        sync: false
